title: About the Author
author: Talitha
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Find out more about my work and my background in my online portfolio! I love animals, especially cats! Married to the love of my life, Franz-David Schmidt, and enjoy playing boardgames with my husband and family and friends.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
